### ISSUE TITLE
initializing stack allocated object

### ISSUE THREAD

**Issue by arakov** [ELENA-LANG/elena-lang#10]
```
#var(type:mssgarray,size:10) properties.
```

may be it should be something like:

```
#var(type:mssgarray) properties := MessageArray new &length:10.
```

but will be still implemented as stack allocated object.

how to define the structure size, call the constructor and so on ? 

probably we could specify the method hint to indicate the default constructor???

**Comment by arakov** [comment]
Special constructor:

    #var(type:mssgarray) properties &length:10.

and in the class

    #class MessageArray
    {
         #constructor(stacksafe)init &length:aLength
         [
         ]

**Comment by arakov** [comment]
So init could be called implicitly for stack allocated object

**Comment by arakov** [comment]
The problem is how to prevent it from direct call, or it should contains the code to check if the object was already stack allocated

**Comment by bencz** [comment]
Maybe a checkbit ?

**Comment by arakov** [comment]
Yes of course, something like this, the question is where should be this bit

**Comment by arakov** [comment]
After thinking, I will take another way.

Leave the syntax the same

     #var(type:mssgarray) properties := MessageArray new &length:10.

But use "compiler magic" / source code optimization : compiler may know that embeddable constructor is called and replace it with optimized call

**Comment by arakov** [comment]
fixed

**Comment by arakov** [comment]
done
