### ISSUE TITLE
infinity

### ISSUE THREAD

**Issue by arakov** [ELENA-LANG/elena-lang#109]
infinity

**Comment by bencz** [comment]
?

**Comment by arakov** [comment]
For example in C# you have the following constat : double.PositiveInfinity

**Comment by arakov** [comment]
See as well - rosettacode.org/wiki/Infinity

**Comment by bencz** [comment]
Oh, ok!!
This infinity!!

**Comment by bencz** [comment]
It is really simple, I just don't know the best local to put it...., because all of this values are constants...
```
    /// Negates the value
    stacksafe negative
        = 0.0r - theValue.
        
    /// Negative infinity 
    stacksafe negativeInfinity 
        = -1.0r / 0.0r. 
        
    /// Positive infinity 
    stacksafe positiveInfinity 
        = 1.0r / 0.0r. 
        
    /// NaN
    stacksafe NaN
        = 0.0r / 0.0r.
```

**Comment by arakov** [comment]
that's why it is marked as **good first issue** :smile:

**Comment by bencz** [comment]
ahhahahah 👍 
For test, I just leaved this methods inside RealNumber class...., probably, this is the better place for this methods!

**Comment by arakov** [comment]
Yes, it should be RealNumber constructor

**Comment by bencz** [comment]
I will work on this issue

**Comment by arakov** [comment]
Yes, it should be embeddable constructor:

    embeddable constructor positiveInfinity 
        = ...

**Comment by arakov** [comment]
closing
