### ISSUE TITLE
round to specified decimal places

### ISSUE THREAD

**Issue by arakov** [ELENA-LANG/elena-lang#113]
round to specified decimal places

**Comment by bencz** [comment]
An e-mail from 17/12/2016:

    Hi, but in this case it is not rounding, it is truncating. For rounding (ceiling) :
 
    #method MyRound &real:aValue &int:aSig
    [
        #var(real) a := aValue.
        #var(bool) neg := false.
        (aValue is &negative)?
            [
                a := a * -1.0r.
                neg := true.
            ].
           
        #var(int) b := 10 power:aSig.
        #var(int)c := (a * b + 0.5r) roundedInt.
 
        a := c realDiv:b.
 
        ^(neg) ?[ a * -1.0r ] ! [ a ].         
    ]

**Comment by arakov** [comment]
:smile:

**Comment by bencz** [comment]
I will work on this issue

**Comment by arakov** [comment]
already done
