### ISSUE TITLE
truncate to specified decimal places

### ISSUE THREAD

**Issue by arakov** [ELENA-LANG/elena-lang#114]
truncate to specified decimal places

**Comment by bencz** [comment]
An e-mail from 17/12/2016:

For truncating:
 
    #method MyRound &real:aValue &int:aSig
    [
        #var(real) a := aValue.
        #var(bool) neg := false.
        (aValue is &negative)?
            [
                a := a * -1.0r.
                neg := true.
            ].
           
        #var(int) b := 10 power:aSig.
        #var(real) c := (a * b) integer. // returns the integer part of the real number
 
        a := c / b.
 
        ^(neg) ?[ a * -1.0r ] ! [ a ].         
    ]

**Comment by bencz** [comment]
I will work on this issue

**Comment by arakov** [comment]
already done
