### ISSUE TITLE
fixed size array field

### ISSUE THREAD

**Issue by arakov** [ELENA-LANG/elena-lang#123]
support fixed array : #field(type:shortarray,size:260)cFileName.

**Comment by arakov** [comment]
implemented

**Comment by arakov** [comment]
reopening

**Comment by arakov** [comment]
the new syntax:

    shortarray<260> cFileName.

or

    type<ShortArray,260> cFileName.

**Comment by arakov** [comment]
Dynamic array:

    short<> cFileName.

or

    type<ShortNumber,> cFileName.

**Comment by bencz** [comment]
It's looks like C++/CLI array... https://www.codeproject.com/Articles/7704/Arrays-in-C-CLI

**Comment by arakov** [comment]
Yes, it is general idea to be similar to template declaration (from grammar point of view), because I cannot use square brackets for array declarations

**Comment by bencz** [comment]
A interesting thing of C++/CLI array is the "rank", that means the dimension of array...

"rank [optional]
The number of dimensions of the array. Must be 1."

**Comment by bencz** [comment]
About the syntax.... I think this way, it becomes more readable:

```
array<ShortNumber, 2> arr.
arr[0][1] := 0.
```

I think using the term "type" does not seem like you're creating an array ...

**Comment by arakov** [comment]
But you do not create an array, You just declare a variable / field

**Comment by arakov** [comment]
And you already can create an array using array a:

    array<IntNumber> a := int&(3).

which syntax I would like to change to something like this:

    array<IntNumber> a := int<>(3).

**Comment by arakov** [comment]
Done.

**Comment by arakov** [comment]
reopening

**Comment by arakov** [comment]
fixed
