### ISSUE TITLE
Solution Explorer

### ISSUE THREAD

**Issue by arakov** [ELENA-LANG/elena-lang#13]
Menu - View - Solution Explorer

**Comment by bencz** [comment]
Maybe now is a good time to use that item from your todo:
in version 2.0.0: ( switch to xml config files ), not just the config files but the project format to...
use a xml or yaml ?

**Comment by arakov** [comment]
yes, it would be good idea

**Comment by arakov** [comment]
implemented

**Comment by bencz** [comment]
:+1: 
Now it's really more easy to navigate into project files!!!
Thanks!!!
