### ISSUE TITLE
#define statement

### ISSUE THREAD

**Issue by arakov** [ELENA-LANG/elena-lang#143]
_#define_ statement name is misleading, probable it should be renamed into _#using_ or _#include_

**Comment by bencz** [comment]
Or #import

**Comment by arakov** [comment]
So we have three variants: _#import_, _#using_ and _#include_

**Comment by bencz** [comment]
Recalling a comment made at the forum to develop operating systems .... what is the complexity of removing the "#" of keywords?

**Comment by arakov** [comment]
I'm not going to do it. How are you going to distinguish class as keyword from class as variable name?

**Comment by bencz** [comment]
Ohh, it is true!!
No problem! :)

**Comment by arakov** [comment]
There is actually no rational reason why it is better to write something like

    class @class

than

    #class class

**Comment by bencz** [comment]
For me, it's ok :), I also understand the reason!
I like the syntax with '#' :+1:

**Comment by arakov** [comment]
I guess the best would be #import, and #define be kept for backward compatibility

**Comment by arakov** [comment]
implemented
