### ISSUE TITLE
An acccess violation error : Memo.set&caption[1]

### ISSUE THREAD

**Issue by arakov** [ELENA-LANG/elena-lang#175]
In my debugger, I created a Memo, and when I try to set the text of
memo, in another class ( not in constructor... ) I got a access
violation... ( with old and the new 'current' version ) in debugger, the
access violation occurs when cursor go to 'set' method

theTextField set &caption:"oi".

**Comment by bencz** [comment]
Solved...
The problem is, I have created a #field with name X, and when I instantiate the variable X, I have created whit "#var" keyword, with same name..., so, the system can't determine the instance of object...

```C
#class Sample
{
    #field theValue.

    #constructor new
    [
        #var theValue := List new.
    ]
}
```

**Comment by arakov** [comment]
fixed

**Comment by bencz** [comment]
I'm thinking... 
Why compiler allow to have a field and a variable with same name ?

Sent from my ASUS

-------- Original Message --------

**Comment by arakov** [comment]
It is normal behavior for c++. In C# you may re-declare it as well, though you have to provide an additional keyword. 

That's why I introduced the prefix "the", which is used only for the class fields. Local fields may have prefix "a" or be without.
