### ISSUE TITLE
Closure : auto boxing / unboxing local variables

### ISSUE THREAD

**Issue by arakov** [ELENA-LANG/elena-lang#190]
If the local variable is assigned inside the closure, the compiler should replace it with wrapper, box it and unbox after the operation is finished. E.g. 

```
    #var(type:bool) registerExpected := true.
    content run &token_dfa:dfa &each:aToken
    [
        (aToken == "%")
            ? [
                registerExpected := true.
            ]
            ! [
            ]

    ].
```

**Comment by bencz** [comment]
In several points of the code, I had used the run&each, but as I received many warnings due to variables that I changed that were out of run%each, I preferred to change to #loop

**Comment by arakov** [comment]
Yes, in that case, you have to use a dynamic variable. So it is possible to overcome but of course it would be better if the compiler will be able to handle this situation itself .

For example in this code you may write something like:

    #var registerExpected := Boolean new:true.
    content run &token_dfa:dfa &each:aToken
    [
        (aToken == "%")
            ? [
                registerExpected << true.
            ]
            ! [
            ]

    ].

**Comment by arakov** [comment]
done in another ticket

**Comment by arakov** [comment]
already fixed
