### ISSUE TITLE
Adding program forward reference automatically

### ISSUE THREAD

**Issue by arakov** [ELENA-LANG/elena-lang#203]
For console project, the forward to the entry symbol should be created automatically.

So no need to provide it manually.

The name of the entry symbol should be - program

**Comment by bencz** [comment]
This will help a lot, who is beginning to learn / use Elena

**Comment by bencz** [comment]
Maybe create a folder with a 'default' templates, like in VS.
Eg. User created a console project, than, the IDE create a initial file with 'program and with default forward setted automatically

**Comment by bencz** [comment]
An ideia.
Create a new key in cfg file, of template.

"
[prj:template]
template=console.tprj
"

The file console.tprj will contains the default values

**Comment by arakov** [comment]
Yes, there is already project template option : 

    template=console

I do have the same idea to introduce a special forward reference which contains the project namespace

**Comment by bencz** [comment]
Hi! :)
Yes, I mean inside of console template file ( win32_console.cfg ), has some default values... :)

**Comment by arakov** [comment]
implemented
