### ISSUE TITLE
SSE and MMX

### ISSUE THREAD

**Issue by arakov** [ELENA-LANG/elena-lang#207]
The best way to use SSE and MMX is creating some external dll which can be called from ELENA code simply.

Adding it to coreapi is hack, there should be another way

**Comment by bencz** [comment]
Why adding the assembly code with SSE/MMX instructions in coreapi is hacking ?

**Comment by bencz** [comment]
A very useful links about SSE and MMX:
https://www.cs.uaf.edu/2011/fall/cs441/lecture/09_29_SSE.html
http://neilkemp.us/src/sse_tutorial/sse_tutorial.html
https://en.wikibooks.org/wiki/X86_Assembly/SSE
intel80386.com/simd/mmx2-doc.html

**Comment by arakov** [comment]
Because it can be done only if you recompile compiler binaries. Normal user / programmer cannot do it himself. And in general calling coreapi function is tricky and unsafe. There should be much simpler way - using DLL like for sqllite library.

Of course for some cases coreapi may be used for simplicity / optimization. So the answer is - in general it is a bad way, but for some very specific cases it may be ok
