### ISSUE TITLE
exiting the lock statement

### ISSUE THREAD

**Issue by arakov** [ELENA-LANG/elena-lang#223]
Lock is not released if the lock statement has an exit statement

```
#lock (obj)
[
     //...

     ^ true.
]
```

**Comment by arakov** [comment]
The same situation for exiting external block

     #extern
     [
            // ...
           ^ nil.
     ]

**Comment by arakov** [comment]
The same if an exception was thrown, 

try-finally construction should be as light as possible, no exception boxing

**Comment by bencz** [comment]
Maybe use templates for this ?

**Comment by bencz** [comment]
Or create a method to 'hide' the use of try-finally or lock statement... ?

**Comment by arakov** [comment]
I meant, implementation, not the syntax :)

#lock construction contains built-in try-finally block, because if the exception happens inside it, the lock will not be released without it

**Comment by arakov** [comment]
fixed indirectly in the previous releases
