### ISSUE TITLE
Static fields

### ISSUE THREAD

**Issue by arakov** [ELENA-LANG/elena-lang#266]
ELENA should support static fields.

Static fields can be implemented as internal static symbol, e.g. the following code:

```
#class MyClass
{
     #field(static)theField.
     ...
```

should be compiled into:

```
#static MyClass#static1 = $nil.

#class MyClass
{
    ...
```

**Comment by arakov** [comment]
done

**Comment by arakov** [comment]
reopening

**Comment by arakov** [comment]
done

**Comment by arakov** [comment]
Both static and sealed static will be supported.

**sealed static** is only one instance per the whole hierarchy, **static** - one instance per class

**Comment by bencz** [comment]
This could be used for methods too ?

**Comment by arakov** [comment]
I'm thinking about it. I'm opening #350

**Comment by arakov** [comment]
constant static field will be supported:

    class Class1
    {
        const static object theConstant := 5.
    }

it can be assigned only during the class declaration / inheriting:

    class ChildClass :: Class1
    {
        theConstant := 6.
    }

**Comment by arakov** [comment]
static fields are already supported
