### ISSUE TITLE
Module initializers

### ISSUE THREAD

**Issue by arakov** [ELENA-LANG/elena-lang#267]
Module initializer should be implemented

**Comment by arakov** [comment]
A new attribute is introduced : preloaded

    #symbol(preloaded)Loader = (...).

any symbol with preloaded symbol will be automatically invoked on module loading - in stand-alone version it will happens on the program start, for vm client when the module will be first time resolved

**Comment by arakov** [comment]
JITLinker will look if the module contains built-in symbol #preloaded and invoke it (for stand-alone version the invoke code will be added to preload table, for vm client - will be called directly)

**Comment by bencz** [comment]
What exactly ia the proposal of the "preload" ?
A symbol to load a .ini file for example and set the initial properties of system ?

**Comment by arakov** [comment]
Yes, any code which should be called on the program start up.

For example for socket programming WSAStartUp should be called before any operation. Of course it could be done manually, but it is much cleaner solution to call this code automatically

**Comment by arakov** [comment]
done
