### ISSUE TITLE
Basic value hash code function reimplementation

### ISSUE THREAD

**Issue by arakov** [ELENA-LANG/elena-lang#27]
Replace the current simple hash function code with better one (probably based on C# implementation) for LiteralValue / IntNumber / ... 

What about Integer / Real / ... ?

**Comment by bencz** [comment]
The method "GetHashCode" from .Net, is internally implemented like this:

`*(U32*)pReturnValue = ((((U32)pThis_) >> 2) * 2654435761UL);`

For a example, the Int64 hash method in .net: [](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Int64.cs#L82)

**Comment by bencz** [comment]
Why not hashing the pointer of object, returning a MD5 ?

**Comment by arakov** [comment]
Why not

**Comment by bencz** [comment]
I will look at it... so, whit this will be not necessary to implement a hash method to every type...

**Comment by arakov** [comment]
It should be fast enough, similar to C#, and I guess they have a separate function for strings, decimal and so on

**Comment by bencz** [comment]
MD5 or SHA-256, has some ready to use algorithms, that is REALLY fast, of course, not so fast as a simple XOR...., but, it is really fast....

Yes, in .net has a different hash implementations for Strings, Uint, Int, datetime.....
Look at this hashs:
1. http://referencesource.microsoft.com/#mscorlib/system/string.cs,789
2. http://referencesource.microsoft.com/#mscorlib/system/datetime.cs,834
3. http://referencesource.microsoft.com/#mscorlib/system/int32.cs,86

...
So, if we implement a method on object class, that returns a hash from address of object pointer ( can be a XOR like this: *(U32*)pReturnValue = ((((U32)pThis_) >> 2) * 2654435761UL); )

**Comment by bencz** [comment]
Look at this MD5 implementation in Assembly... https://www.nayuki.io/page/fast-md5-hash-implementation-in-x86-assembly

**Comment by arakov** [comment]
OK. The function probably should be implemented in coreapi module in assembly

**Comment by bencz** [comment]
Ok, I will look at this...
Probably I will use this MD5 hash implementation: https://www.nayuki.io/res/fast-md5-hash-implementation-in-x86-assembly/md5-fast-x86.S

Has some problem for you, to use this one ?

**Comment by arakov** [comment]
No problem. Unfortunately it uses different assembly syntax which is supported by asm2binx. We could use it

**Comment by bencz** [comment]
Ok, no problem!
I can convert from AT&T syntax to Intel syntax!
...

The general idea of md5 calculation from object pointer:

1. Get object pointer
2. Get the bytes from object pointer
3. Reverse the bytes
4. Calculate the MD5 HASH
5. Convert the stages from MD5 hashing to hex string
6. Return hex string from MD5

**Comment by arakov** [comment]
done
