### ISSUE TITLE
Optimization : operation with structure fields (byte or short)

### ISSUE THREAD

**Issue by arakov** [ELENA-LANG/elena-lang#278]
#class(struct) MyClass
    {
        #field(byte)n1.
        #field(byte)n2.
        #field(byte)n3.
            #field(byte)n4.
        
        #method init
        [
            n2 := 3.
            n1 := 2.
        ]
    }

**Comment by bencz** [comment]
This can be used to read for example a binary into struct ?
something like this:

// just some p-code ( to get the ideia )
#var xx := MyClass new. //
fread(file, &MyClass, sizeof(MyClass));

**Comment by bencz** [comment]
I suppose it is not possible, as once you told me, that it is necessary to attribute value by value, correct?
And also I believe that it is not possible, due to the memory alignment, correct?

**Comment by arakov** [comment]
It is possible. In 2.x the data wrapper was introduced. See for example system'io'Stream:

    theStream read &bytearray:aBuffer &vint:aBufferLength.:

where vint is virtually a reference to int

**Comment by bencz** [comment]
Ok, but, If in the case of complex structs, like this:

#class(struct) MyClass
{
#field(int) v1.
#field(real) v2.
#field(??) class2.
}

#class(struct) MyClass2
{
#field(int) vv1.
#field(real) vv2.
}

It's possible too ?

**Comment by arakov** [comment]
Yes it will be a bit more tricky. You have to declare a new subject associated with your structure.

    #subject class2 = Class2.
    #class(struct) Class2
    {
        #field(int) vv1.
        #field(real) vv2.   
    }
   
    #class(struct) MyClass
    {
         #field(int) v1.
         #field(real) v2.
         #field(class2) class2.
    }

**Comment by arakov** [comment]
I just found the bug :) I will look at it:

    #import system.
    
    #subject class2 = Class2.
    #class(struct) Class2
    {
        #field(int) vv1.
        #field(real) vv2.   
        
        #constructor new
        [
            vv1 := 2.
            vv2 := 3.0r.
        ]    
    }
    
    #class(struct) MyClass
    {
         #field(int) v1.
         #field(real) v2.
         #field(class2) class2.
     
         #method init
         [
             class2 := Class2 new.
         ]
         
         #method get = class2.
    }
    
    #symbol program =
    [
        #var o := MyClass new init.
        
        #var f := o get. // here the error
    ].

**Comment by arakov** [comment]
The bug was fixed - 791d1db4a72c9a3cec4e840a246a8f168cf9d48f

**Comment by bencz** [comment]
Hi Alex!
There is a error on debugger display, look:
![untitled](https://cloud.githubusercontent.com/assets/1174448/21347994/3c7af760-c692-11e6-8405-8faeddac6a29.png)

**Comment by arakov** [comment]
Hi,

I know, I will fix it later

**Comment by arakov** [comment]
done
