### ISSUE TITLE
"a b := c." ambiguity

### ISSUE THREAD

**Issue by arakov** [ELENA-LANG/elena-lang#291]
warn if for the expression "a b := c." - a could be considered both as symbol (variable,...) and subject.

**Comment by bencz** [comment]
Hi Alex!
I not understand, why its necessary to considerate the object as symbol and
subject ?

**Comment by arakov** [comment]
Old style was deterministic  : 

     #var(int) b := c.

where int - is a subject ("type"), b is a variable name.

Now new style:

    int b := c.

This expression can be treated two ways:
First - int is a type, b is a new variable name.
Second - int is a variable name, b is a property, and this case it could be compiled as follow:

     int set&b:c.

**Comment by arakov** [comment]
it is similar to c ambiguity:

     a * b;  // either a is a type or a is a variable

**Comment by arakov** [comment]
done
