### ISSUE TITLE
Recursive extension

### ISSUE THREAD

**Issue by arakov** [ELENA-LANG/elena-lang#304]
Currently recursive extension is allowed. E.g.

    extension op
    {
        fibonacci
        [
            if (self < 2)
            [ 
                ^ self.
            ];
            [
                ^ (self - 1) fibonacci + (self - 2) fibonacci.   // !! here the extension is called inside itself
            ].
        ]
    }
 
This could be a problem if extension method overrides dynamically existing one. E.g.

    class MyClass
    {
        myMethod []
    }
    
    extension myExtension
    {
      myMethod 
      [
          self myMethod .  // extension method is called recursively instead of original one
      ]
    }
    // ...
    program 
    [
        var o := MyClass new.

        o myMethod.  // !! extension method is called
    ].

**Comment by bencz** [comment]
class base1
{
    doSomething [ ]
}

class base2 :: base1
{
    doSomething [ $self doSomething. ]
}

class UseBase :: base2
{
    constructor new [ ]
}

This cause a recursion too ( maybe I did something wrong... ? )

**Comment by arakov** [comment]
To call the parent method **$super** variable should be used:

    class base2 :: base1
    {
       doSomething [ $super doSomething ]
    }

**Comment by bencz** [comment]
Oh!
I did not know about the $super

**Comment by arakov** [comment]
prefix attribute direct can be used
