### ISSUE TITLE
wrong result with equals and not equals operator for long numbers

### ISSUE THREAD

**Issue by bencz** [ELENA-LANG/elena-lang#310]
this code produce this result:

program =
[
    long v := 38654842193l.
    int i := 0.
    while(i < 63)
    [
        long a := 1l.
        long b := v && a.
        if(b != 0l) [ console writeLine:i. ].
        i := i + 1.
    ].
]

the expected result for this code is:
0
1
2
6
8
10
12
17
32
35

but, the result from elena code is:
0
1
2
6
8
10
12
17

**Comment by arakov** [comment]
could you please verify your code once again. It always returns the same result because v is not changed

**Comment by bencz** [comment]
sorry, the variable a is wrong
long a := 1l << i.

**Comment by arakov** [comment]
fixed, please verify and close

**Comment by bencz** [comment]
Result is correctly
