### ISSUE TITLE
access violation when parameter is $nil

### ISSUE THREAD

**Issue by bencz** [ELENA-LANG/elena-lang#311]
This code rise an access violation, on "if(aA != $nil)"

```
class Test
{
    int theA.
    
    constructor new int:a [ theA := a ]
    
    callSomething
    [
        int i := 0.
        while(i < 3)
        [
            var v := i.
            if(i == 2) [ v := $nil. ].
            $self doSomething value:v.
        ].
    ]
    
    doSomething value:aA 
    [
        if(aA != $nil)
          [ ^(aA + 1). ]; [ ^theA * 2. ].
          
    ]
}
```

**Comment by arakov** [comment]
It is expected behavior.  $nil is zero reference. Very often equal method sends a dispatching message to the parameter which raises an access violation.

So you should either write something like this:

    if($nil != aA) // in this case the compiler will replace
   
or use nil symbol (which is an object encapsulating $nil)

     if(aA != nil)

**Comment by bencz** [comment]
Thanks! 👍
