### ISSUE TITLE
Fixing Linux version

### ISSUE THREAD

**Issue by arakov** [ELENA-LANG/elena-lang#319]
Since the latest changes, Linux version of the compiler is broken

**Comment by bencz** [comment]
What about change to another IDE ? ... the codeblocks is really bugged :(

**Comment by arakov** [comment]
Why not, we could support several project types. Do you know one?

**Comment by bencz** [comment]
There some really good C++ IDEs

- NetBeans
- Eclipse
- CLion ( it's not free )

**Comment by arakov** [comment]
Moving ELENA Linux version to NetBeans

**Comment by arakov** [comment]
done

**Comment by arakov** [comment]
reopening : critical exceptions and MT

**Comment by arakov** [comment]
fixed
