### ISSUE TITLE
Compilation never ends

### ISSUE THREAD

**Issue by bencz** [ELENA-LANG/elena-lang#325]
When trying to compile the project [DotNetProject](https://github.com/bencz/DotNetProject/tree/master/DotNetPELib/DotNetPELib_test_all_sources), both by the IDE and by command line, the compiler apparently enters an infinite loop in the compilation of the file "OpCode.l"

**Comment by arakov** [comment]
Yes, I can reproduce the issue. I will look at it

**Comment by arakov** [comment]
The bug happens only for release version. Looks like some uninitialized data

**Comment by arakov** [comment]
fixed
