### ISSUE TITLE
Source file with full path causes a forever loop in IDE

### ISSUE THREAD

**Issue by bencz** [ELENA-LANG/elena-lang#329]
When the new source file is added to the project, some times the IDE add the full path directory of source, when try to open the project, the IDE enters into forever loop.

**Comment by bencz** [comment]
Should be better, the IDE always save with relative path... ?

**Comment by arakov** [comment]
Yes, I think it would be better. But the best solution would be to introduce an option if IDE should save relative or full path 😄 :

**Comment by bencz** [comment]
look at #331 about relative paths

**Comment by arakov** [comment]
I think if the bug fixed, you may close it
