### ISSUE TITLE
IDE not save the file with relative path

### ISSUE THREAD

**Issue by bencz** [ELENA-LANG/elena-lang#332]
Simulating the problem:

1. Create a new project
2. Create a new file
3. Press CTRL + S ( save the new source file )
4. Save the project

In files tag of ini file, the sources will be created with fullpath.
Looking at source, in method "includeSource" the variable _model->project.path is empty in this first time, so, the method makeRelativePath can't calculate the relative path

**Comment by arakov** [comment]
Ok, thanks. Will you fix it or should I do it?

**Comment by bencz** [comment]
It's so simple to create a pull request
At this line: https://github.com/ELENA-LANG/elena-lang/blob/master/elenasrc2/ide/appwindow.cpp#L826
The if should be: 

`if (_model->project.name.isEmpty() && !_model->currentDoc->status.included)`

**Comment by arakov** [comment]
Well done :+1:

**Comment by arakov** [comment]
fixing
