### ISSUE TITLE
long to int raise a index is out of range exception

### ISSUE THREAD

**Issue by bencz** [ELENA-LANG/elena-lang#335]
After implementation of uint type, this code cause a index is out of range exception

```
import system.
import extensions.

program =
[
    long rva := 339302427672l.
    int result := ((rva && 0FFFFFFFFh) toInt).
].
```

**Comment by arakov** [comment]
I will look at it

**Comment by arakov** [comment]
Quick fix will be to use long constant:

    long rva := 339302427672l.
    
    int result := ((rva && 4294967295l) toInt).

The problem that int32=0FFFFFFFFh should be correctly converted to int64=0FFFFFFFFFFFFFFFF
and as a result you get the same number.

uint vs int is a long story :smile: I will fix it later after I finish multimethods implementation which will be huge change :smile:

**Comment by arakov** [comment]
The correct code is:

    import system.
    import extensions.
    
    public program
    [
        long rva := 339302427672l.
        int result := rva && 0FFFFFFFFh toUInt.
    ]
