### ISSUE TITLE
Macro definition in asm2binx

### ISSUE THREAD

**Issue by bencz** [ELENA-LANG/elena-lang#336]
Implement support for macro processing in asm2binx
Design idea:

```
defmacro <MACRO NAME>([ARG1], [ARG2], ...)
     // this will make a literal translation just... if you pass "ebx" on "arg1", the macro processor will convert ARG1 to eax
    mov eax, ARG1
    mov eax, (10*arg2) // evaluate the expression with arg2 as variable... 
endmacro
```

The idea is implement this to reduce the code size for md5 implementation, referenced to #27

**Comment by arakov** [comment]
:smile: It will require preprocessor. I don't mind :smile:

**Comment by bencz** [comment]
I will implement this...
It will be something interesting for me to implement and study some things! :)

**Comment by arakov** [comment]
👍

**Comment by arakov** [comment]
closing.
