### ISSUE TITLE
Static methods

### ISSUE THREAD

**Issue by arakov** [ELENA-LANG/elena-lang#350]
Currently a class class may have only constructor methods. 

E.g.

    class MyClass
    {
         constructor new []
    }

if we look in MyClass#class in ecv:

    @parent system'Object
    @flag elSealed
    @flag elStateless
    @method MyClass#class.#new
    @method MyClass#class.new

Should it be possible to declare a static method?

    class MyClass
    {
         constructor new []

         static proceed []
    }

So it could be used like this:

    MyClass proceed.

**Comment by bencz** [comment]
Ok, but, if we look at the OO programming standards ( in SmallTalk ), there is no way to create a static method...
A some solution ( in my point of view ) is compile the satatic method  like this:

```
class MyClass
{
    static staticMethod []
}

var a := (MyClass new) staticMethod.
```
So, the compiler automatically create the instance, to be able to call the static method...

**Comment by arakov** [comment]
Not exactly. Both in Smalltalk and ELENA a class is a normal object, a singleton. From this point of view, a constructor is considered like a normal method, which returns the instance of this object. So nothing forbid us to have another method declared in the class.

**Comment by arakov** [comment]
So you do not need to instantiate the class to call the static method. Actually it makes no sense and produce an extra load for GC, we create an object which is not used

**Comment by arakov** [comment]
There is major difference with a normal class methods. In the following code:

     class MyClass
     {
         static method1[]
     }

     class MyChild :: MyClass
     {
     }
    
the following code:

     MyClass method1. // this code works
     MyChild method1. // this code fails

The reason is MyChild#class does not inherit MyClass#class

**Comment by arakov** [comment]
done
