### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by bencz** [ELENA-LANG/elena-lang#386]
How about implement a ARM support ?
This will be useful to try to implement a Android or iOS support!!

**Comment by arakov** [comment]
It could be interesting. I will mark it as help-wanted

**Comment by bencz** [comment]
* http://infocenter.arm.com/help/topic/com.arm.doc.qrc0001l/QRC0001_UAL.pdf
* https://doc.lagout.org/programmation/asm/ARM%20Assembly%20Language_%20Fundamentals%20and%20Techniques%20%282nd%20ed.%29%20%5BHohl%20%26%20Hinds%202014-10-20%5D.pdf
* https://godbolt.org/

**Comment by bencz** [comment]
* https://github.com/bencz/AndroidARM

**Comment by arakov** [comment]
ELENA 6.0 - the simplest program is compiled and executed for aarch64!

**Comment by arakov** [comment]
done
