### ISSUE TITLE
compile-time message resolving : classes with custom dispatcher

### ISSUE THREAD

**Issue by arakov** [ELENA-LANG/elena-lang#415]
In the following code:

    import extensions; 
    
    public program()
    {
        var s := "2";
        
        var n := convertor.toInt(s) // an exception is raised
    } 

The code above does not work because there are ambiguity between "convertorOp.toInt[1]" and the convertor proper method.

What the best way to resolve this ambiguity ?

**Comment by bencz** [comment]
Maybe, create a new class just to work with conversions...

class convert
[
public toInt( val ) [ ^converter toInt(val). ]
].

Alexandre S. Bencz

+55 {15} 997-980-511

**Comment by arakov** [comment]
Yes, the class exists - extensions'convertor - the problem is that for particular message - "toInt[1]" there is an ambiguity : there is an extension and an implicit method.

**Comment by bencz** [comment]
Maybe, do something like .net ?

Convert.ToInt32(x);
Convert.ToInt64(x);
...

Alexandre S. Bencz

+55 {15} 997-980-511

**Comment by arakov** [comment]
already fixed
