### ISSUE TITLE
IDE Crashes

### ISSUE THREAD

**Issue by mva1985** [ELENA-LANG/elena-lang#442]
every time I go to load one of the example programs on Windows 7 the IDE just completely closes down.  I'm using the 3.4.1 version

**Comment by arakov** [comment]
Hi. could you tell me the name of example it crashes?

**Comment by mva1985** [comment]
sorry for taking so long to reply...  I have been having the same issue while using versions 3.1.1 and 3.2.0 and 3.4.1

I start elide.exe and try to load an example file.  So far I've tried several of the examples and I get the same result of the IDE just crashing completely.  No error messages are displayed

**Comment by arakov** [comment]
The project file format was changed in 3.4.0, but it should still generate an error that the project file has an invalid structure. It works on Windows 10. Currently I cannot test it on Windows 7. But I will try this weekend on my old computer. Could you try this version built with SDK 8.1? - https://github.com/ELENA-LANG/elena-lang/releases/download/v3.4.2/elena.3.4.2_sdk8.zip

**Comment by arakov** [comment]
SDK version works fine on Windows 7

**Comment by mva1985** [comment]
I'll give it a shot when I get home...  thanks

**Comment by arakov** [comment]
closing as per previous message
