### ISSUE TITLE
Release 3.4.2 build error

### ISSUE THREAD

**Issue by bencz** [ELENA-LANG/elena-lang#450]
After build the last "release" from master, using the "vs_release.bar", when I try to build the libs I got the following error:

$ rebuild_lib.bat

E:\programming\elena-lang_master>bin\sg dat\sg\syntax.txt
ELENA command line syntax generator 3.4.1 (C)2005-2015 by Alexei Rakov
generating...
saving...

E:\programming\elena-lang_master>move dat\sg\syntax.dat bin
        1 file(s) moved.

E:\programming\elena-lang_master>bin\og dat\og\rules.txt
ELENA command line optimization table generator 3.4.1 (C)2012-15 by Alexei Rakov

Successfully created

E:\programming\elena-lang_master>move dat\og\rules.dat bin
        1 file(s) moved.

E:\programming\elena-lang_master>bin\asm2binx src34\core\core_routines.esm lib34\system
ELENA Assembler Compiler 3.4.5 (C)2011-2017 by Alexei Rakov
Successfully compiled

E:\programming\elena-lang_master>bin\asm2binx asm\x32\core.asm bin\x32
ELENA Assembler Compiler 3.4.5 (C)2011-2017 by Alexei Rakov
Successfully compiled

E:\programming\elena-lang_master>bin\asm2binx asm\x32\corex.asm bin\x32
ELENA Assembler Compiler 3.4.5 (C)2011-2017 by Alexei Rakov
Successfully compiled

E:\programming\elena-lang_master>bin\asm2binx asm\x32\coreapi.asm bin\x32
ELENA Assembler Compiler 3.4.5 (C)2011-2017 by Alexei Rakov
Successfully compiled

E:\programming\elena-lang_master>bin\asm2binx asm\x32\core_vm.asm bin\x32
ELENA Assembler Compiler 3.4.5 (C)2011-2017 by Alexei Rakov
Successfully compiled

E:\programming\elena-lang_master>bin\asm2binx asm\x32\core_win.asm bin\x32
ELENA Assembler Compiler 3.4.5 (C)2011-2017 by Alexei Rakov
Successfully compiled

E:\programming\elena-lang_master>rem bin\asm2binx -amd64 asm\amd64\core.asm bin\amd64

E:\programming\elena-lang_master>rem bin\asm2binx -amd64 asm\amd64\core_win.asm bin\amd64

E:\programming\elena-lang_master>rem bin\asm2binx -amd64 asm\amd64\coreapi.asm bin\amd64

E:\programming\elena-lang_master>bin\elc src34\system\system.prj
ELENA Command-line compiler 3.4.200 (C)2005-2018 by Alex Rakov

Project : src34\system\system.prj, Platform: library
Cleaning up...
Compiling...
Parsing system
Compiling system
types.l
object.l
basic.l
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
templates.l
control.l
compiling template...
compiling template...
compiling template...
memory.l
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
win32_pointers.l
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
win32_strings.l
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
dynamic.l
extensions.l
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
exceptions.l
compiling template...
events.l
console.l
compiling template...
compiling template...
win32_app.l
compiling template...
compiling template...
compiling template...
collections\list.l
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
collections\queues.l
compiling template...
compiling template...
collections\tuples.l
collections\maps.l
math\math.l
calendar\win32_datetime.l
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
calendar\dates.l
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
text\encoder.l
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
text\win32_encoder.l
compiling template...
compiling template...
text\textbuffer.l
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
culture\win32_locale.l
culture\win32_stringculture.l
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
io\common.l
compiling template...
compiling template...
io\ioexceptions.l
io\streamreader.l
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
io\streamwriter.l
io\win32_console.l
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
io\win32_files.l
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
io\files.l
compiling template...
Parsing system'routines
Compiling system'routines
routines\enumerables.l
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
compiling template...
routines\patterns.l
Parsing system'routines'stex
linker: error 205: Invalid file 'routines\stex\strong_patterns.l'

Compiled with errors

**Comment by arakov** [comment]
Hi Alexandre, please verify if the error is gone now. I forgot to add one file to git

**Comment by bencz** [comment]
Not yet

`
...
Parsing system'threading
Compiling system'threading
threading\win32_handlers.l
compiling template...
threading\thread.l
threading\thread_patterns.l
Parsing system'net
linker: error 205: Invalid file 'net\win32_common.l'

Compiled with errors
`

**Comment by arakov** [comment]
try again 😄

**Comment by bencz** [comment]
Success!
Everything compiled correctly now!

**Comment by arakov** [comment]
👍
