### ISSUE TITLE
Error in identity matrix with size >= 100

### ISSUE THREAD

**Issue by bencz** [ELENA-LANG/elena-lang#465]
I did a small test today, if you try to generate a matrix with the dimensions >= 100, the program don't print the result matrix.

**Comment by arakov** [comment]
Please, provide a code

**Comment by bencz** [comment]
Hi Alex
I did the test in matrix sample

**Comment by arakov** [comment]
It is a quite obscure bug, for example the following code works quite fine:

    import extensions'math.
     
    public program
    [
        var r := RealMatrix new(100,100); populate(:i:j)<int,int,real>
                ( (i == j)iif(1.0r,0.0r) ).
    ]

We will see

**Comment by bencz** [comment]
This code:

`import extensions.
import extensions'math.

public symbol program = 
[
    T<RealMatrix> r := RealMatrix new(100,100); populate(:i:j)<int,int,real>
            ( (i == j)iif(1.0r,0.0r) ).
    
    console writeLine:(r toLiteral).
    console readChar.
].`

Not work... When I try to debug, I get this erro:
![image](https://user-images.githubusercontent.com/1174448/46723721-d94cbb00-cc4e-11e8-889b-0ac98e89c36a.png)

**Comment by bencz** [comment]
This seems to be some error, with the stack allocated variables

**Comment by arakov** [comment]
I will look, currently it looks like the array is too big for the stack, we will see

**Comment by arakov** [comment]
No this issue is too big object. There is a limitation on how big your object can be. For example the following code works:

import extensions.
import extensions'math.

public program
[
    auto r := RealMatrix new(100,100); populate(:i:j)<int,int,real>
            ( (i == j)iif(1.0r,0.0r) ).
    
    0 till:100 do(:i)
    [
        0 till:100 do(:j)
        [
            console print(r[i][j], ", ")
        ].
        
        console writeLine.
    ].
    
    console readChar
]

**Comment by arakov** [comment]
It is an out of memory exception. It has nothing to do with matrix size. The error happens when the matrix is converted to _literal_. The issue will be fixed later (if ever) - see #466
