### ISSUE TITLE
interpretation mode

### ISSUE THREAD

**Issue by bencz** [ELENA-LANG/elena-lang#469]
We could analyze an idea to implement a interpretation mode, where, all eCode is interpreted, instead of using JIT to generate machine code and then run the system.
The idea behind this is to be able to port the compiler and VM to other platforms and operating systems without the great trump of having to carry assembly code, or, run on embed systems

**Comment by arakov** [comment]
Yes, it is possible but hardly plausible. It will probably be too slow for any practical use. Though why not if someone want to try

**Comment by arakov** [comment]
the issue is postponed indefinitely
