### ISSUE TITLE
hello.l(3:1): error 147: Invalid attribute 'public'

### ISSUE THREAD

**Issue by petelomax** [ELENA-LANG/elena-lang#479]
**Describe the bug**
compilation error

**To Reproduce**
http://rosettacode.org/wiki/Hello_world/Graphical#Elena

**Comment by arakov** [comment]
It looks like you use old version.

Could you please tell me the compiler version. You may easy do it, just type elc in the command line

**Comment by petelomax** [comment]
4.0.269
     On Wednesday, 4 September 2019, 11:41:47 BST, Aleksey Rakov <notifications@github.com> wrote:  
 
 
It looks like you use old version.

Could you please tell me the compiler version. You may easy do it, just type elc in the command line

**Comment by arakov** [comment]
it is very strange. Is there only one instance of the compiler installed? Could you attach your project?
By me it is compiled without any error (https://github.com/ELENA-LANG/elena-lang/releases/tag/v4.0.5)

**Comment by petelomax** [comment]
<configuration>
 <files>
 <module>
 <include>hello.l</include>
 </module>
 </files>
</configuration>
     On Wednesday, 4 September 2019, 20:11:43 BST, Aleksey Rakov <notifications@github.com> wrote:  
 
 
it is very strange. Is there only one instance of the compiler installed? Could you attach your project?
By me it is compiled without any error (https://github.com/ELENA-LANG/elena-lang/releases/tag/v4.0.5)

**Comment by arakov** [comment]
Your project is lacking *project* section

    <project>
        <executable>your executable name</executable>
        <namespace>your namespace</namespace>
        <template>gui</template>
    </project>

**Comment by petelomax** [comment]
elide hangs when I press run, and "elc hello" now gets:
ELENA Command-line compiler 4.0.269 (C)2005-2019 by Alex Rakov

Project : , Platform: library
Cleaning up...
Compiling...
Parsing unnamed
linker: error 205: Invalid file 'hello'

Compiled with errors
     On Friday, 6 September 2019, 08:28:21 BST, Aleksey Rakov <notifications@github.com> wrote:  
 
 
Your project is lacking project section
<project>    <executable>your executable name</executable>    <namespace>your namespace</namespace>    <template>gui</template></project>

**Comment by arakov** [comment]
Sorry, I was not very clear. The proect file should be like this:

    <configuration>
     <project>
       <executable>hello.exe</executable>
       <namespace>hello</namespace>
       <template>gui</template>
     </project>
     <files>
      <module>
       <include>hello.l</include>
      </module>
     </files>
    </configuration>

**Comment by petelomax** [comment]
That is exactly what I ended up with (apart from slightly different indentation), still getting the exact same errors.
     On Saturday, 7 September 2019, 12:12:43 BST, Aleksey Rakov <notifications@github.com> wrote:  
 
 
Sorry, I was not very clear. The proect file should be like this:
<configuration> <project>   <executable>hello.exe</executable>   <namespace>hello</namespace>   <template>gui</template> </project> <files>  <module>   <include>hello.l</include>  </module> </files></configuration>

**Comment by arakov** [comment]
[guitest.zip](https://github.com/ELENA-LANG/elena-lang/files/3586590/guitest.zip)
Could you please try to compile this project?

**Comment by arakov** [comment]
To compile the project write:

    elc guitest.prj

**Comment by petelomax** [comment]
Ah, progress! - elc now works fine. The stupid thing I missed was the .prj (slaps head). However, elide can still hang:
Delete hello.exe and start elide, open guitest.prj if rqd, then press run/F9 *before* compile/Ctrl-F9 and it just hangs.     On Saturday, 7 September 2019, 13:14:05 BST, Aleksey Rakov <notifications@github.com> wrote:  
 
 
To compile the project write:
elc guitest.prj

**Comment by arakov** [comment]
Fixed

**Comment by arakov** [comment]
Could you verify if the issue is solved?
