### ISSUE TITLE
Migrating functions from assembly to C

### ISSUE THREAD

**Issue by bencz** [ELENA-LANG/elena-lang#502]
Can you post to show, how to implement the functions directly in C in the language runtime?
for example, how to implement these two functions directly at the runtime?

`procedure coreapi'strtochararray`
`procedure coreapi'strtoint`

Thanks

**Comment by arakov** [comment]
For better performance, some of the functions should be left in assembly (these two for example). I'm not planning to implement linking C compiled modules (obj) into ELENA directly. Maybe later.

So to use C function you have to create DLL and declare these functions.

    #define EXTERN_DLL_EXPORT extern "C" __declspec(dllexport)
    
    EXTERN_DLL_EXPORT int MyCFunction(int arg)
    {
         return arg + 2;
    }

So now you could call the function from ELENA

    public program()
    {
         int r := extern mydll.MyCFunction(2);
    }

**Comment by arakov** [comment]
closing - assuming the question is answered
