### ISSUE TITLE
ldiv / lmul implementation

### ISSUE THREAD

**Issue by arakov** [ELENA-LANG/elena-lang#53]
ldiv / lmul opcode implementation should be optimized

**Comment by bencz** [comment]
About "ldiv", don't have so much to optimize... ( I believe that ldiv and lmul is "long long" ), take a look in this:  https://github.com/lattera/glibc/blob/master/sysdeps/wordsize-32/divdi3.c#L274 and in this: https://godbolt.org/z/HRx7je ... your implementation of ldiv and lmul is pretty good!!!

**Comment by arakov** [comment]
so, I will close it
