### ISSUE TITLE
Generics

### ISSUE THREAD

**Issue by arakov** [ELENA-LANG/elena-lang#54]
Currently Arrays / Variables for each type should be explicitly declared.

this should be somehow generalized, for example as some kind of generic type class

**Comment by arakov** [comment]
Property template

     #template(target:field) prop
     {
         #method set : value
         [
             $target := value.
         ]
         
         #method get = $target.
     }
     
     #class MyClass
     {
         #field(prop:MyField,type:int)myField.
     }

usage

        #var x := MyClass new.
        
        x MyField := 12. // the same as x set &MyField:12
        
        #var f := x MyField.

**Comment by bencz** [comment]
:+1:

**Comment by arakov** [comment]
Method template

    #template(target:method) vrnprop
    {
       #method(stacksafe,type:int,embeddable,suppress:w3) get
       [
            #var(type:int)aLength.
            $target eval &vint:aLength.
            
            ^ aLength.
       ]
    }    

Applying

    #class(sealed) MyClass
    {
        #method(stacksafe,vrnprop:Length) readLength &vint:aLength
        [
            aLength << -1.
        ]
    }

Usage

        #var(type:my_class) m := MyClass new.
        
        #var(type:int) l2 := m Length.

**Comment by arakov** [comment]
Class templates will be used to declare primitive types, arrays, closures and so on

**Comment by arakov** [comment]
Class templates:

    #template dispatchable
    {
        /// Dispatches the verb to the target with a specified subject
        #method cast : verb &to:target = target::verb eval &template_subj:$self.
    
        /// Dispatches the verb to the target object with generic subject
        #method cast : aVerb &to:aTarget &with:aParam = 
             aTarget::aVerb eval:aParam &template_subj:$self.
    }

**Comment by arakov** [comment]
done
