### ISSUE TITLE
class already exist

### ISSUE THREAD

**Issue by YairBybabayov** [ELENA-LANG/elena-lang#679]
**Describe the bug**
when Im including the source file twice and compile between the 2 i get the error class already exist
**To Reproduce**
Write a snippet code

**Expected behavior**
compilation error
**Please complete the following information:**
 - OS: [e.g. Windows 10] Windows 11
 - Version [e.g. ELC 3.4.248 / ELENA API 3.4.50]ELENA API 6.3.3

**Additional context**

**Comment by YairBybabayov** [comment]
just open a project file from the examples

compile it more then once until you can include it again

include it and compile and the problem accrue

**Comment by arakov** [comment]
Fixed in ELENA 6.3.1
