### ISSUE TITLE
ELENAVM : display if VM is 32 or 64 bit on Windows?

### ISSUE THREAD

**Issue by arakov** [ELENA-LANG/elena-lang#680]
1. **Is your feature request related to a problem? Please describe.**
When VM is initialized, the greeting is displayed

     ELENA VM 6.3.5 (C)2022-2024 by Aleksey Rakov

The information if it is 32 or 64 bit version must be displayed

**Describe the solution you'd like**
ELENAVMMachine :: init method must be modified to display the type of binary, something like

     ELENA VM 6.3.5 (32 bit) (C)2022-2024 by Aleksey Rakov

**Comment by YairBybabayov** [comment]
When VM is initialized

when does it happening?

I think I solved it (and all the test are running well) but how do I test if it works?

**Comment by arakov** [comment]
You can test it.

If you go to examples60/console/helloworld and complie with virtual profile:

    elena-cli -lvirtual helloworld.prj 

where -l select a profile. As a result you can have several configurations inside a single project file.

It will be 32 bit version

If you use 64 bit compiler- elena64-cli - it will be 64 bit version

**Comment by arakov** [comment]
Fixed. Thank you Yair once again
